// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auwvfuotpysditrngcle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1d3ZmdW90cHlzZGl0cm5nY2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTQ0OTYsImV4cCI6MjA2NTQ5MDQ5Nn0.SP1qnW3gDtAV4-qCnvm744nrON2zIlwvEWLcn0j57Ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);